language: node_js

branches:
  only:
    - master

git:
  depth: 5

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run build

deploy:
  provider: heroku
  skip_cleanup: true
  api_key:
    secure: vo8NSkza+MrFb8WXIFKgwRFQ/ICurIL3GMtLY7KrHCSmsLLJtsmz1lSPkn6niJ9AU3ZIy/XqZAcycdPNwjDmDknz7rLnXv/Jr9f7dlSRvUBdTxvNFwFXt48mteT2T/OQ3f5Dzqae0J0N3hP5UBewqZyMzBD2aT/hT6kVvWti0zpXI+7h1SWZPGKaOeLraVRZ6FojjbjfTTH3UlxYX68sUYxU29kBl6KBwMpNb4r8TKbRACtnKutPsvQ9iur2AOI5bIROZoW5ErBv+8RY7ws+mEboogVjlWlVXhE1C2y7XMg1iBL2ek+oAWxuZ7xpa/YvQHmLVpQH7qB6jKfna8XMK3NZ+8oW2/u4KsSTM2t2QLJRTmqeVsNVljNhew7xfxkaY/7xA/J5i6hGoQYvJ0WitwxDW7H44zZTgtr33AosP/Abde2pEJbL7D6Oa2hh5UCAdpu6oJ3FaIXa6ui495QdtPfl/CBhSIrVeOEd57ryps87SAH9sIvG0ZWV/bfSYLQ9pVVFHXliGa3UbriKvbYpha4zYFRNFPTZwEPgD65cQiKyQ01TS5L0ovN1lPt7jtwZscZ+fbTLv6JI9iRX2OTRJJ7iaYE8DxeYt5DrvJqZkxE3IIuRAZkuzfM4l72NpuXEaT10tWRxEQm0IW0of1BH67HRFj6QmumGKZZsnvmd794=
  app: giftdibs-browser
  on:
    repo: giftdibs/giftdibs-browser
    branch: master

cache:
  directories:
    - /home/travis/.rvm/
    - node_modules
