language: node_js

branches:
  only:
    - master

git:
  depth: 5

before_script:
  - npm install -g @angular/cli

script:
  - ng lint
  - npm run build

cache:
  directories:
    - /home/travis/.rvm/
    - node_modules
