name: Test

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 5
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
      - name: Install and run tests
        run: |
          npm ci
          npx -p @angular/cli@11 ng lint
          npx -p @angular/cli@11 ng build
          bash <(curl -s https://codecov.io/bash)
